//File Name: auth.js
//Path: src/actions/actionTypes/
//Description: All auth action types are initialized here as constants and exported
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILED = 'AUTH_SIGNUP_FAILED';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD';
export const AUTH_FORGOT_SUCCESS = 'AUTH_FORGOT_SUCCESS';
export const AUTH_INVALID_EMAIL = 'AUTH_INVALID_EMAIL';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';
export const AUTH_CHANGE_PASSWORD_SUCCESS = 'AUTH_CHANGE_PASSWORD_SUCCESS';
export const AUTH_CHANGE_PASSWORD_FAILED = 'AUTH_CHANGE_PASSWORD_FAILED';
export const AUTH_EDIT_PROFILE = 'AUTH_EDIT_PROFILE';
export const AUTH_EDIT_PROFILE_SUCCESS = 'AUTH_EDIT_PROFILE_SUCCESS';
export const AUTH_EDIT_PROFILE_FAILED = 'AUTH_EDIT_PROFILE_FAILED';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS';
export const CHECK_TOKEN_FAILED = 'CHECK_TOKEN_FAILED';
export const GET_TOKEN = 'GET_TOKEN';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILED = 'UPLOAD_IMAGE_FAILED';